[Appearance]
style=Fusion
icon_theme=Papirus-Dark
color_scheme_path=/usr/share/qt6ct/colors/darker.conf
custom_palette=false
standard_dialogs=default

[Interface]
cursor_flash_time=1000
menus_have_icons=true
