---
- name: Install base packages
  ansible.builtin.include_role:
    name: paru_install
  vars:
    paru_packages: "{{ pacman_packages }}"
    paru_label: base

- name: Remove legacy packages
  become: true
  community.general.pacman:
    name: "{{ packages_absent }}"
    state: absent
