---
- name: Install OpenSSH
  become: true
  community.general.pacman:
    name: openssh
    state: present

- name: Enable and start sshd
  become: true
  ansible.builtin.systemd:
    name: sshd
    enabled: true
    state: started
