-- Generated by nwg-displays on 2026-07-24 at 13:44:25. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1366x768@59.97",
    position = "3286x161",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1366x0",
    scale = 1.0
})
