fastfetch -c $HOME/.config/fastfetch/fastfetch.jsonc

ZSH_THEME="minimal"

plugins=(git)

source $HOME/.oh-my-zsh/oh-my-zsh.sh

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
