---
- name: Check if fnm is installed
  ansible.builtin.command:
    cmd: pacman -Q fnm
  register: fnm_check
  failed_when: false
  changed_when: false

- name: Install fnm via paru
  ansible.builtin.shell:
    cmd: "paru -S --needed --noconfirm fnm"
    executable: /bin/bash
  when: fnm_check.rc != 0
  changed_when: true

- name: Check for a default Node installed via fnm
  ansible.builtin.shell:
    cmd: 'eval "$(fnm env)" && fnm ls | grep -q default'
    executable: /bin/bash
  register: node_check
  failed_when: false
  changed_when: false

- name: Install Node.js LTS via fnm and set as default
  ansible.builtin.shell:
    cmd: 'eval "$(fnm env)" && fnm install --lts && fnm default lts-latest'
    executable: /bin/bash
  when: node_check.rc != 0
  changed_when: true
